# Generated by Django 3.1.5 on 2021-02-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=250, verbose_name='комментарии'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Обработанный', 'Processed'), ('Необработанный', 'Unprocessed')], default='Unprocessed', max_length=14, verbose_name='статус заказа'),
        ),
    ]
