# Generated by Django 3.1.5 on 2021-02-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20210205_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Обработанный', 'Processed'), ('Необработанный', 'Unprocessed')], default='Необработанный', max_length=14, verbose_name='статус заказа'),
        ),
    ]
