# Generated by Django 3.1.5 on 2021-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20210205_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processed', 'Обработанный'), ('Unprocessed', 'Необработанный')], default='Unprocessed', max_length=14, verbose_name='статус заказа'),
        ),
    ]
