# Generated by Django 3.1.5 on 2021-02-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20210205_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Обработанный', 'Обработанный'), ('Необработанный', 'Необработанный')], default='Необработанный', max_length=14, verbose_name='статус заказа'),
        ),
    ]
