# Generated by Django 3.1.5 on 2021-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20210205_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PR', 'Обработанный'), ('UP', 'Необработанный')], default='UP', max_length=2, verbose_name='статус заказа'),
        ),
    ]
