# Generated by Django 3.1.5 on 2021-02-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20210205_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CH', 'Наличными'), ('CR', 'Банковская карта'), ('TR', 'Электронный перевод'), ('CC', 'Криптовалютный перевод')], max_length=2, verbose_name='способ оплаты'),
        ),
    ]
